import type { Service, Package, BlogPost, Testimonial } from '../types';

export const SERVICES: Service[] = [
  {
    id: 'kilo-yonetimi',
    title: 'Kilo Yönetimi',
    description: 'Bilimsel temelli, sürdürülebilir kilo verme veya alma programları. Metabolizmanıza özel, açlık hissi yaratmayan planlar.',
    emoji: '⚖️',
    features: ['Vücut kompozisyon analizi', 'Kişiye özel beslenme planı', 'Haftalık takip seansları', 'Alışveriş listesi ve tarifler', 'Motivasyon desteği'],
  },
  {
    id: 'sporcu-beslenmesi',
    title: 'Sporcu Beslenmesi',
    description: 'Performansınızı artıran, kas gelişimini destekleyen ve toparlanmayı hızlandıran spor odaklı beslenme planları.',
    emoji: '🏃',
    features: ['Antrenman öncesi/sonrası beslenme', 'Protein ve makro hesaplama', 'Yarışma öncesi hazırlık', 'Hidrasyon stratejisi', 'Takviye ürün danışmanlığı'],
  },
  {
    id: 'hastalik-yonetimi',
    title: 'Hastalık Yönetimi',
    description: 'Diyabet, kolesterol, tansiyon ve sindirim sorunları için medikal beslenme tedavisi.',
    emoji: '💊',
    features: ['Diyabet beslenme planı', 'Kolesterol yönetimi', 'İrritabl bağırsak sendromu', 'Tansiyon dostu beslenme', 'Tahlil yorumu'],
  },
  {
    id: 'online-danismanlik',
    title: 'Online Danışmanlık',
    description: 'Nerede olursanız olun video görüşme ile profesyonel destek. WhatsApp takibi ve anlık mesajlaşma.',
    emoji: '💻',
    features: ['Video görüşme seansları', 'WhatsApp günlük takip', 'Dijital beslenme günlüğü', 'Online ölçüm takibi', 'E-posta destek'],
  },
  {
    id: 'cocuk-beslenmesi',
    title: 'Çocuk & Ergen Beslenmesi',
    description: 'Büyüme ve gelişme döneminde doğru beslenme alışkanlıkları. Obezite ve seçici yeme sorunları.',
    emoji: '👶',
    features: ['Büyüme gelişim takibi', 'Okul çağı beslenme planı', 'Seçici yeme terapisi', 'Aile beslenme eğitimi', 'Sporcu çocuk planı'],
  },
  {
    id: 'gebelik-beslenmesi',
    title: 'Gebelik Beslenmesi',
    description: 'Anne adayları için gebelik öncesi, gebelik ve emzirme dönemlerine özel beslenme rehberliği.',
    emoji: '🤰',
    features: ['Gebelik öncesi hazırlık', 'Trimester bazlı beslenme', 'Bulantı ve reflü yönetimi', 'Emzirme dönemi beslenmesi', 'Doğum sonrası toparlanma'],
  },
];

export const PACKAGES: Package[] = [
  {
    id: 'baslangic',
    name: 'Başlangıç',
    description: 'Yeni başlayanlar için temel destek',
    price: 1499,
    period: 'aylık (4 hafta)',
    highlighted: false,
    features: [
      '1 Yüz Yüze veya Online Görüşme',
      'Kişiye Özel Beslenme Planı',
      'Besin Değerleri Analizi',
      'E-posta Destek',
      'Diyet Takip Formu',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'Kapsamlı takip ve sürekli destek',
    price: 2999,
    period: 'aylık (4 hafta)',
    highlighted: true,
    badge: '⭐ En Popüler',
    features: [
      '4 Görüşme (Haftalık)',
      'Kişisel Beslenme & Egzersiz Planı',
      'Haftalık Ölçüm Takibi',
      'WhatsApp Destek (Hafta içi)',
      'Tarif Önerileri & Alışveriş Listesi',
      'Kan Tahlili Yorumu',
      'Motivasyon Seansı',
    ],
  },
  {
    id: 'vip',
    name: 'VIP',
    description: 'Sınırsız destek ve tam kişiselleştirme',
    price: 5499,
    period: 'aylık (4 hafta)',
    highlighted: false,
    features: [
      'Sınırsız Görüşme',
      'Tam Kişisel Program',
      'Günlük WhatsApp Takibi',
      '7/24 Mesaj Desteği',
      'Özel Tarif Kitabı',
      'Tahlil & İlaç Yönetimi',
      'Aile Beslenme Danışmanlığı',
      'Öncelikli Randevu Hakkı',
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: '10 Sağlıklı Kahvaltı Önerisi ile Güne Enerjik Başlayın',
    slug: 'saglikli-kahvalti-onerileri',
    excerpt: 'Güne doğru başlamak için protein, sağlıklı yağ ve kompleks karbonhidrat içeren kahvaltı seçenekleri...',
    content: 'Kahvaltı günün en önemli öğünüdür. Doğru besinlerle başladığınızda enerji seviyeniz gün boyu stabil kalır...',
    category: 'Beslenme',
    date: '5 Ocak 2025',
    readTime: 5,
    emoji: '🥗',
  },
  {
    id: 2,
    title: 'Şeker Tüketimini Azaltmanın 5 Etkili Yolu',
    slug: 'seker-tuketimini-azaltma',
    excerpt: 'Gizli şekerler ve sağlıklı alternatifler hakkında bilmeniz gereken her şey...',
    content: 'Şeker bağımlılığı günümüzün en yaygın beslenme sorunlarından biri. İşlenmiş gıdalardaki gizli şekerleri fark etmek...',
    category: 'Sağlıklı Yaşam',
    date: '28 Aralık 2024',
    readTime: 7,
    emoji: '🍬',
  },
  {
    id: 3,
    title: 'Sporcu Beslenmesinde Proteinin Önemi ve Günlük İhtiyaç',
    slug: 'sporcu-beslenmesinde-protein',
    excerpt: 'Antrenman öncesi ve sonrası beslenme stratejileri, protein kaynakları ve zamanlama rehberi...',
    content: 'Egzersiz yapan bireyler için protein ihtiyacı sedanter bireylerden farklıdır. Kas sentezi için...',
    category: 'Sporcu Beslenmesi',
    date: '20 Aralık 2024',
    readTime: 6,
    emoji: '💪',
  },
  {
    id: 4,
    title: 'Diyabet ve Beslenme: Kan Şekerini Dengede Tutmanın Yolları',
    slug: 'diyabet-ve-beslenme',
    excerpt: 'Glisemik indeks, öğün zamanlaması ve diyabet dostu besinler hakkında kapsamlı rehber...',
    content: 'Tip 2 diyabette beslenme tedavisi ilaç kadar önemlidir. Glisemik indeksi düşük besinler...',
    category: 'Hastalık Yönetimi',
    date: '15 Aralık 2024',
    readTime: 9,
    emoji: '🩺',
  },
  {
    id: 5,
    title: 'Çocuklarda Sağlıklı Beslenme Alışkanlığı Nasıl Kazandırılır?',
    slug: 'cocuklarda-saglikli-beslenme',
    excerpt: 'Seçici yiyen çocuklarla başa çıkma stratejileri ve oyunlaştırılmış beslenme önerileri...',
    content: 'Çocukluk döneminde kazanılan beslenme alışkanlıkları ömür boyu etkili olur. Ebeveynlerin rolü...',
    category: 'Çocuk Beslenmesi',
    date: '8 Aralık 2024',
    readTime: 8,
    emoji: '👶',
  },
  {
    id: 6,
    title: 'Gebelikte Doğru Beslenme: Trimester Trimester Rehber',
    slug: 'gebelikte-dogru-beslenme',
    excerpt: 'Her üç trimester için özel beslenme önerileri, kaçınılması gereken besinler ve vitamin takviyesi...',
    content: 'Gebelik döneminde annenin beslenmesi hem annenin hem bebeğin sağlığını doğrudan etkiler...',
    category: 'Gebelik Beslenmesi',
    date: '1 Aralık 2024',
    readTime: 10,
    emoji: '🤰',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: 'Ayşe K.',
    initials: 'AK',
    age: 34,
    service: 'Kilo Yönetimi',
    quote: 'Zeynep Hanım sayesinde 3 ayda 12 kilo verdim ama en önemlisi bunu açlık çekmeden yaptım. Program o kadar kişiseldi ki hiç zorlanmadım. Artık yemekle ilişkim tamamen değişti.',
    rating: 5,
    result: '-12 kg',
    resultLabel: '3 ayda',
  },
  {
    id: 2,
    name: 'Mehmet S.',
    initials: 'MS',
    age: 52,
    service: 'Diyabet Yönetimi',
    quote: 'Diyabet teşhisi aldıktan sonra beslenme konusunda çok kayboldum. Zeynep Hanım hem kan şekerimi dengeledi hem de lezzetli yiyecekler önerdi. 6 ayda ilaç dozum yarıya düştü.',
    rating: 5,
    result: 'HbA1c',
    resultLabel: '%8.2 → %6.1',
  },
  {
    id: 3,
    name: 'Elif Y.',
    initials: 'EY',
    age: 28,
    service: 'Sporcu Beslenmesi',
    quote: 'Maraton koşucusuyum ve doğru beslenme konusunda çok bilgi kirliliği vardı. Zeynep Hanım bana net, bilimsel ve uygulanabilir bir plan verdi. Kişisel rekorumu kırdım!',
    rating: 5,
    result: '+18%',
    resultLabel: 'Performans artışı',
  },
];
